<?PHP
echo "<h3>please be informed that the website is 
under maintainance enjoy world's  number one 
crypto trading platform</h3>";
echo "<H3>PLEASE CONNECT WITH US ON SOCIAL NETWORKS
 TO BUY OR SELL CRYPTO<br><br></h3>";
/*$stmt->close();
$conn->close();	
}*/

?>
<a href=""><H3>facebook</H3></a><a href=""><H3>
whatsapp</H1></a><a href="ZEDBITCOINS@GMAIL.COM"><H3>
EMAIL</H3></a>
<body>
<h3 align="center"color="green">&copy;zedbitcoins</h3>
</body>